services:
  web1:
    image: nginx:alpine
    container_name: web1
    volumes:
      - ./server1/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - appnet

  web2:
    image: nginx:alpine
    container_name: web2
    volumes:
      - ./server2/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - appnet

  lb:
    image: nginx:alpine
    container_name: load-balancer
    depends_on:
      - web1
      - web2
    ports:
      - "8080:80"
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
