apiVersion: v1
kind: Service
metadata:
  name: web1-service
spec:
  selector:
    app: web1
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web2-service
spec:
  selector:
    app: web2
  ports:
    - port: 80
      targetPort: 80
