apiVersion: v1
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>Server 2</title>
      </head>
      <body>
        <h1>Hola amikos soy el server #2</h1>
      </body>
    </html>
kind: ConfigMap
metadata:
  name: web2-html
