apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
        - name: web2
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web2-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: web2-html
          configMap:
            name: web2-html
