nname: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - assignment-03

env:
  APPLICATION_NAME: assignment-app
  ENVIRONMENT_NAME: Assignment-app-env
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Debug workspace
        run: |
          echo "PWD:"
          pwd
          echo "FILES:"
          ls -la
          echo "package.json?"
          test -f package.json && echo "OK" || echo "MISSING"
          echo "package-lock.json?"
          test -f package-lock.json && echo "OK" || echo "MISSING"

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Build Docker image
        run: docker build -t assignment-app:${{ github.sha }} .

      - name: Create deployment package
        run: |
          zip -r ../deploy.zip . -x "node_modules/*" "dist/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          application_name: ${{ env.APPLICATION_NAME }}
          environment_name: ${{ env.ENVIRONMENT_NAME }}
          version_label: assignment-${{ github.sha }}
          deployment_package: deploy.zip